In [8]:
import numpy as np

# Función para restar dos vectores
def subtract_vectors(v1, v2):
    return np.array([v1[i] - v2[i] for i in range(3)])

# Función para normalizar un vector
def normalize(v):
    norm = np.linalg.norm(v)
    if norm == 0: 
        return v
    return v / norm

# Función para calcular el producto cruzado entre dos vectores
def cross_product(v1, v2):
    return np.cross(v1, v2)

# Función para crear la matriz de vista
def create_view_matrix(Camera, Target, Up):
    # Restar los vectores para obtener z (dirección de la vista)
    z = subtract_vectors(Camera, Target)
    z = normalize(z)
    
    # Calcular el eje X (derecha)
    x = cross_product(Up, z)
    x = normalize(x)
    
    # Calcular el eje Y (arriba corregido)
    y = cross_product(z, x)
    
    # Crear la matriz de vista
    view_matrix = np.zeros((4, 4))
    
    # Asignar los valores correspondientes
    view_matrix[0, 0] = x[0]
    view_matrix[0, 1] = y[0]
    view_matrix[0, 2] = z[0]
    view_matrix[1, 0] = x[1]
    view_matrix[1, 1] = y[1]
    view_matrix[1, 2] = z[1]
    view_matrix[2, 0] = x[2]
    view_matrix[2, 1] = y[2]
    view_matrix[2, 2] = z[2]
    
    # Traslación en la matriz de vista
    view_matrix[0, 3] = -(np.dot(x, Camera))
    view_matrix[1, 3] = -(np.dot(y, Camera))
    view_matrix[2, 3] = -(np.dot(z, Camera))
    
    # El valor en la última columna
    view_matrix[3, 3] = 1
    
    return view_matrix

# Definir los vectores Camera, Target y Up
Camera = np.array([1.0, 2.0, 3.0])  # Cámara
Target = np.array([0.0, 0.0, 0.0])  # Objetivo
Up = np.array([0.0, 1.0, 0.0])     # Vector "arriba"

# Generar la matriz de vista
view_matrix = create_view_matrix(Camera, Target, Up)

# Imprimir la matriz de vista
print("Matriz de vista:")
print(view_matrix)


Matriz de vista:
[[ 9.48683298e-01 -1.69030851e-01  2.67261242e-01 -1.11022302e-16]
 [ 0.00000000e+00  8.45154255e-01  5.34522484e-01 -2.22044605e-16]
 [-3.16227766e-01 -5.07092553e-01  8.01783726e-01 -3.74165739e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
